import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./component/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // icons: {
  //   icon: [
  //     {
  //       rel: "icon",
  //       type: "image/png",
  //       sizes: "32x32",
  //       url: "./favicon.ico",
  //       href: "./favicon.ico",
  //     },
  //   ],
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="./favicon.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />
        {children}
        <p className="bg-white text-black py-3 mb-5 text-center absolute w-full bottom-[-80px]">
          Footer Section of the page
        </p>
      </body>
    </html>
  );
}
